app.controller("main",function($scope,$http){
        var winHeight = $(window).height();
        $(window).scroll(function(){
            if($(window).scrollTop()>winHeight){
                $(".back").fadeIn(300);
            }else{
                $(".back").fadeOut(300);
            }
        });
        $scope.listImg = [
            {
                src:"img/dadou.png"
            },
            {
                src:"img/tudou.png"
            },
            {
                src:"img/dami.png"
            },
            {
                src:"img/lanmei.png"
            },
            {
                src:"img/yanmai.png"
            }
        ];

        $scope.guopinList = [
            {
                src:"img/shizi.png",
                p:"铁钉柿子精选500g",
                span:"99.00"
            },
            {
                src:"img/lanmei.png",
                p:"蓝莓鲜果2000g",
                span:"68.00"
            },
            {
                src:"img/tizi.png",
                p:"红提子1000g",
                span:"46.00"
            },
            {
                src:"img/taijiubaotao.png",
                p:"大久保桃1000g",
                span:"29.00"
            },
            {
                src:"img/huangxing.png",
                p:"黄杏500g",
                span:"28.00"
            }
        ];
        $scope.shucaiList = [
            {
                src:"img/tudou1.png",
                p:"土豆1000g",
                span:"99.00"
            },
            {
                src:"img/qiezi.png",
                p:"茄子500g",
                span:"68.00"
            },
            {
                src:"img/lajiao.png",
                p:"辣椒500g",
                span:"46.00"
            },
            {
                src:"img/baicai.png",
                p:"白菜400g",
                span:"29.00"
            },
            {
                src:"img/mogu.png",
                p:"蘑菇500g",
                span:"28.00"
            }
        ];
        $scope.guwuList = [
            {
                src:"img/dadou.png",
                p:"大豆1000g",
                span:"99.00"
            },
            {
                src:"img/yumi.png",
                p:"玉米500g",
                span:"68.00"
            },
            {
                src:"img/xiaomai.png",
                p:"小麦500g",
                span:"46.00"
            },
            {
                src:"img/dami1.png",
                p:"大米400g",
                span:"29.00"
            },
            {
                src:"img/xiaomi.png",
                p:"小米500g",
                span:"28.00"
            }
        ];
        $scope.qindanList = [
            {
                src:"img/jidan.png",
                p:"鸡蛋1000g",
                span:"99.00"
            },
            {
                src:"img/jirou.png",
                p:"鸡肉500g",
                span:"68.00"
            },
            {
                src:"img/yangrou.png",
                p:"羊肉500g",
                span:"46.00"
            },
            {
                src:"img/yarou.png",
                p:"鸭肉400g",
                span:"29.00"
            },
            {
                src:"img/zhurou.png",
                p:"猪肉500g",
                span:"28.00"
            }
        ];
        $scope.qitaList = [
            {
                src:"img/tianzao.png",
                p:"甜枣1000g",
                span:"99.00"
            },
            {
                src:"img/heizao.png",
                p:"东北黑枣500g",
                span:"68.00"
            },
            {
                src:"img/shizibing.png",
                p:"柿子饼500g",
                span:"46.00"
            },
            {
                src:"img/songzi.png",
                p:"松子400g",
                span:"29.00"
            },
            {
                src:"img/hongguniang.png",
                p:"红姑娘500g",
                span:"28.00"
            }
        ];
});