app.controller('list',function($scope){
    //分页器事件
    $(".page").createPage({
        pageCount:10,
        current:1,
        backFn:function(p){
        }
    });

    $scope.listNav = {
        first:"谷物",
        second:"大豆"
    };
    $scope.tuijieList = [
        {
            src:"img/dadou1.png",
            p:"大豆精选500g",
            span:"99.00"
        },
        {
            src:"img/feijiyindadou.png",
            p:"非转基因大豆500g",
            span:"99.00"
        },
        {
            src:"img/dongbeihuangdou.png",
            p:"东北大豆精选500g",
            span:"99.00"
        },
        {
            src:"img/dadou2.png",
            p:"大豆精选500g",
            span:"99.00"
        },
        {
            src:"img/huangdou.png",
            p:"黄豆精选500g",
            span:"99.00"
        },
        {
            src:"img/feijiyindadou.png",
            p:"黄豆精选500g",
            span:"99.00"
        },
        {
            src:"img/huangdou2.png",
            p:"黄豆精选500g",
            span:"99.00"
        },
        {
            src:"img/huangdou1.png",
            p:"黄豆精选500g",
            span:"99.00"
        },
        {
            src:"img/dongbeidadou.png",
            p:"黄豆精选500g",
            span:"99.00"
        },
        {
            src:"img/dadou2.png",
            p:"黄豆精选500g",
            span:"99.00"
        },{
            src:"img/huangdou.png",
            p:"黄豆精选500g",
            span:"99.00"
        },
        {
            src:"img/feijiyindadou.png",
            p:"黄豆精选500g",
            span:"99.00"
        },
        {
            src:"img/dongbeihuangdou.png",
            p:"黄豆精选500g",
            span:"99.00"
        },
        {
            src:"img/dadou1.png",
            p:"黄豆精选500g",
            span:"99.00"
        },
        {
            src:"img/huangdou.png",
            p:"黄豆精选500g",
            span:"99.00"
        }
    ];
});